### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by muratorkunkatkat** [Museum-Management-System/MuseumManagementSystem#1]
The bug occurs in table view. Normally, upon clicking a table's columns, the table needs to be sorted automatically. But the bug occurs if the user clicks to an item listed from table, and then goes back, and then clicks one of the table's column to sort. When the user clicks back to sort, the object descriptions opens up again.

**Comment by sibelturgut** [comment]
Fixed. Now sort is available all the time when table is present.
